### PR TITLE
Introduce SafeMath.sub() with revert reason

### PR DESCRIPTION
**Pull request by k06a**
I believe this best-practice could improve revert reasons readability: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v3.0.0/contracts/math/SafeMath.sol#L55

### CODE REVIEW

**Comment by k06a** [comment]
@MicahZoltu the reason is that `sub` underflow is the most popular case of SafeMath failures, reason of which easy to understand to any user. Revert reasons for `add` and `mul` could be useful for token developers for example, but this happens not as  frequent as `sub` failures.

**Comment by MicahZoltu** [comment]
I can see how `sub` reason string would be *more* valuable, but it doesn't quite explain why to *not* include it for add/mul?  Is it that you believe thu additional gas cost of passing a reason string isn't worth it for add/mul?  Or perhaps you wanted to introduce the smallest change, and if accepted you'll then follow-up with the others?

**Comment by k06a** [comment]
@MicahZoltu it seems a gas argument is more relevant to my point of view

**Comment by MicahZoltu** [comment]
I *believe* the gas cost difference will be negligible?  Maybe a dozen gas for pushing the reason onto the stack.  You can do some optimizations to avoid reading the string out of memory until *after* failure if you want to limit it.  Overall, I think that the gas cost savings isn't worth not having revert strings everywhere.

**Comment by k06a** [comment]
@MicahZoltu sure you can introduce `mul` and `add` revert reasons, I at least trying to push `sub` reason to be included. Also interesting to know @nventuro's reason to add reasons only to `sub` and `div` in OZ: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v3.0.0/contracts/math/SafeMath.sol

**Comment by nventuro** [comment]
I left `add` and `mul` out for simplicity's sake: I didn't want to pollute the namespace and documentation with those, since I have yet to find an instance where an overflow isn't, well, an overflow.

On the other hand, `sub` lets you subtract from a value without having to perform a check beforehand, so in that case the error is not an overflow, but rather whatever that value not being large enough means:

```
function transfer(...) {
   require(balance[user] >= amount, "Insufficient balance");
   balance -= amount;
}

function transfer(...) {
   balance.sub(amount, "Insufficient balance");
}
```

There's of course nothing wrong with having those also in `add` and `mul`, I just haven't found it useful yet. I'd love to see an example though!

**Comment by NoahZinsmeister** [comment]
thanks for the suggestion, but ultimately we think that the existing static reason string is sufficient for our use cases, and not worth the gas cost increase.

**Pull request closed without merging**
