### PR TITLE
Prepare for deploying the contracts and build artifacts to npmjs

### PR DESCRIPTION
**Pull request by moodysalem**
- Updated waffle to fix the revert error
- solcVersion is now compilerVersion
- added metadata to package json
- for some reason the gas estimates have changed, but i doubt this means anything. the bytecode that compiling produces has not changed.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I still recommend #56 be included in the release prep, though it was closed so I assume that means it was discussed and decided against.

**Comment by NoahZinsmeister** [comment]
yes @MicahZoltu , we (and more importantly our auditors) are more comfortable with ^0.5 than ^0.6, and `0.5.17` isn't meaningfully different from `0.5.16` in this case.

**Comment by moodysalem** [comment]
Unfortunately we still need it in the pair tests but looks like it's not needed in the fixtures. Since the gas estimates are wrong I went ahead and fixed the two gas tests to check actual gas used

**Comment by moodysalem** [comment]
Deployed v1.0.0-beta.0 artifacts to npm
https://unpkg.com/browse/@uniswap/v2-core@1.0.0-beta.0/

**Comment by NoahZinsmeister** [comment]
`79378` -> `73462` is a nice surprise!

**Pull request merged**
